### ISSUE TITLE
Create paths automatically when not exists

### ISSUE THREAD

**Issue by estudioprogramacaocriativa** [laravel/folio#104]
I'd just finish installation of the Folio package to try it out on an existing  project. After do some configurations I get this error:
![Screenshot 2023-09-02 at 13 15 07](https://github.com/laravel/folio/assets/6819427/8b82bdf9-c5f0-4c26-bc45-63e45475e5a2)

My suggestion is to create the path instead of throws an error 

```
public function registerRoute(string $path, string $uri, array $middleware, ?string $domain): void
    {
        $absolutePath = $path;
        $path = realpath($absolutePath);
        $uri = '/'.ltrim($uri, '/');


        if (! is_dir($path)) {
            mkdir($absolutePath, 0777, true);
        }

        $this->mountPaths[] = $mountPath = new MountPath(
            $path,
            $uri,
            $middleware,
            $domain,
        );

        Route::fallback($this->handler())->name('laravel-folio');
    }
```

**Comment by crynobone** [comment]
This is automatically done for the default path. You should create the folder if you wish to change the location:
https://github.com/laravel/folio/blob/master/src/Console/InstallCommand.php#L45-L52
