### ISSUE TITLE
`index` blade file with deeply nested model route binding not working

### ISSUE THREAD

**Issue by vmiguellima** [laravel/folio#105]
### Folio Version

1.1.0

### Laravel Version

10.10

### PHP Version

8.2.8

### Description

`index` blade file, with deeply nested routes with model binding not working  as expected~~is in a folder using the complete namespace (model location).~~
---

## What's happening?
When trying to use route binding using multiple nested folders:
- `user/[.App.Models.User]/posts/[.App.Models.Post]/index.blade.php`
It returns 404 even if it exists.

Works as expected when using:
- `user/[User]/posts/[Post].blade.php`
- `user/[.App.Models.User]/posts/[.App.Models.Post].blade.php`

#### Working using:
<img width="688" alt="image" src="https://github.com/laravel/folio/assets/33354683/558c4805-bb03-4ebd-bc7b-6600a81ee9e5">

### Steps To Reproduce

Create a simple structure as:

<img width="688" alt="image" src="https://github.com/laravel/folio/assets/33354683/84c595da-6cac-4c9a-a978-17eec2078bc8">

**Comment by nunomaduro** [comment]
@vmiguellima Does your `posts` table have a `user_id`?

**Comment by robw-raviga** [comment]
I'm experiencing the same issue, I have Folio directory structure like this:
```
resources/views/pages/
- [year]/
  - index.blade.php
  - [month]/
    - index.blade.php
    - [date]/
      - index.blade.php
      - [Article:slug].blade.php
```

When I access `/2023`, I get a 404.
When I access `/2023/09`, I get a 404.
When I access `/2023/09/08`, I get a 404.

If I access `/2023/09/06/it-works`, I get the page loaded with `$year`, `$month`, `$date` populated and the Article is found successfully by it's slug.

It seems to be an issue resolving the index in those routes from variable part.

When I run `artisan folio:list`, all the routes show as expected
