### ISSUE TITLE
Folio should work with other template engines (like Twig)

### ISSUE THREAD

**Issue by mmodler** [laravel/folio#110]
Hey,

we set up our first folio project und we prefer using twig (via twigbridge) over blade templates.

Folio don't finds templates with .twig extension. After digging the code a little, i found many hardcoded ".blade.php" refreences.

Wouldn't it be nice if the template extension is configurable via config?

Thanks in advance!

**Comment by driesvints** [comment]
Hi there, right now we don't have any additional plans beyond Blade, sorry.
