### ISSUE TITLE
name route function is not working in folio

### ISSUE THREAD

**Issue by baxt1yor** [laravel/folio#111]
### Folio Version

1.1

### Laravel Version

10.10

### PHP Version

8.2

### Description

<img width="1462" alt="image" src="https://github.com/laravel/folio/assets/52046670/3e54a8ea-d1a1-4be9-8401-325ed7d42b34">
<img width="1335" alt="image" src="https://github.com/laravel/folio/assets/52046670/f253bca1-ce0d-4475-b517-946dd60eb70a">

### Steps To Reproduce

name route function is not working in folio

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
