### ISSUE TITLE
Nested model route binding keeps disabling views

### ISSUE THREAD

**Issue by gdsrmygdsrjr** [laravel/folio#117]
### Folio Version

1.1.3

### Laravel Version

10.28.0

### PHP Version

8.2.10

### Description

When using Folio I'm unable to display a create page when a subfolder [id] exists.
The index page is however correctly displayed.

### Steps To Reproduce

Here's what my pages folder look like:
![Captura de tela 2023-10-10 200036](https://github.com/laravel/folio/assets/10488154/b9a9b774-b47d-40c2-b46c-ddf4339f12a9)

And here's what php artisan folio:list shows:
![Captura de tela 2023-10-10 200443](https://github.com/laravel/folio/assets/10488154/00908ae6-368a-414a-9c06-83663ee5d49f)

The admin/properties/index.blade.php works perfectly
The admin/properties/[id]/index.blade.php works perfectly
The admin/properties/[id]/edit.blade.php works perfectly
The admin/properties/create.blade.php ERROR, it is working as admin/properties/[id]/index.blade.php, as I show below:
![Captura de tela 2023-10-10 200943](https://github.com/laravel/folio/assets/10488154/dd7477b5-d442-4377-bb3a-7e861270fc5b)

If I remove the "admin/properties/[id]" folder the create page is displayed.

**Comment by nunomaduro** [comment]
Can you create an Laravel application that faces this issue, push it to GitHub, an give me the link so I can try it locally please?

**Comment by gdsrmygdsrjr** [comment]
Of course! it's here: [folio-issue-project](https://github.com/gdsrmygdsrjr/folio-issue-project)

**Comment by nunomaduro** [comment]
Duplicated of https://github.com/laravel/folio/issues/120.
