### ISSUE TITLE
Empty segments in multi-segment wildcard views are not possible

### ISSUE THREAD

**Issue by inmanturbo** [laravel/folio#118]
### Folio Version

1.1.3

### Laravel Version

10.4.1

### PHP Version

8.2.11

### Description

Consider the following view: `resources/views/pages/users/[...ids].blade.php`

```blade
<ul>
    @forelse(\App\Models\User::whereIn('id', $ids)->get() as $user)
       <li>{{ $user->email }}</li>
    @empty
       <li>No users available</li>
    @endforelse
</ul>
```

When you browse to `/users` you might expect to see 'No users available', however instead you will get `404`.

### Steps To Reproduce

Install folio and paste the above contents into  `resources/views/pages/users/[...ids].blade.php`, then browse to '/users' in your application

**Comment by driesvints** [comment]
Seems you already sent in a PR so let's see how it goes. Thanks 👍
