### ISSUE TITLE
Missing URI prefix when calling `php artisan folio:list`

### ISSUE THREAD

**Issue by jozydapozy** [laravel/folio#125]
### Folio Version

1.1.4

### Laravel Version

10.32.1

### PHP Version

8.2.4

### Description

When I run `php artisan folio:list`, the returned path is missing the URI-prefix when specified. 

I get this:
`GET        /test ......`

I expect the result to be this:
`GET        /foo/test ......`

### Steps To Reproduce

Put this method in your `FolioServiceProvider`:
```php
   /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        Folio::path(resource_path('foobar'))->middleware([
            '*' => [
                //
            ],
        ])->uri('foo/');
    }
```

run `php artisan folio:list`

**Comment by crynobone** [comment]
I was able to replicate this issue with basic installation.
