### ISSUE TITLE
Check if foo.blade.php file_exists for static route before taking /[param] for account?

### ISSUE THREAD

**Issue by pronode** [laravel/folio#137]
If we have such dir structure:
```
/pages
   about.blade.php
   /[Post-slug]
       index.blade.php
```
navigating to `/about` should - in my opinion - load `about.blade.php` instead of looking for a Post with `slug = 'about'`.

It works correctly if we make `/about` dir and put `index.blade.php` inside but wouldn't the above solution be more convenient?

**Comment by pronode** [comment]
I searched through the closed issues and I've found similar ones with `[param].blade.php` file inside the same directory as `foo.blade.php` so the navigation to /foo fails.
Please consider changing the convention because it's quite annoying to have 6 different `index.blade.php` tabs opened in the editor :)
And thanks for all the work of course!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by pronode** [comment]
This is clearly not a question for support channel. This is related to the mechanics of the library.
The special case should take priority over the general case. If creating `/foo/index.blade.php` works then `/foo.blade.php` should work as well...

**Comment by inmanturbo** [comment]
@pronode the file checker/loader pipeline works a lot like middleware. You can see an example how to easily customize it for your app it in this (merged) pr:

https://github.com/laravel/folio/pull/113#issue-1924711034

**Comment by mrcsmcln** [comment]
This really feels like a bug to me. The only workaround I've been able to find is by replacing this:

```
pages/
    about.blade.php
    [Post]/
         index.blade.php
```

with this:

```
pages/
    about/
        index.blade.php
    [Post]/
        index.blade.php
```

With a lot of top-level routes, that become messy pretty quickly and involves a ton of `index.blade.php` files.

Any chance we could reconsider opening this issue?
