### ISSUE TITLE
Add support for dynamic route name

### ISSUE THREAD

**Issue by wassim** [laravel/folio#138]
I'm trying to localize my app with Folio without creating duplicated lang directories inside /pages

So far I came up with this, but the problem is that localized Folio routes are being overwritten by each others and using the `route()` helper leads to the same url. Is there a way to suffix route names with dynamic value, in my case would be the current locale?

```php
Folio::path(resource_path('views/pages'))
    ->uri('en')
    ->middleware([
        '*' => ['lang:en'],
    ]);

Folio::path(resource_path('views/pages'))
    ->uri('fr')
    ->middleware([
        '*' => ['lang:fr'],
    ]);
```

lang middleware
```php
public function handle(Request $request, Closure $next, string $lang): Response
{
    // Set application locale
    app()->setLocale($lang);

    // Remember the last known locale for automatic redirects
    if ($request->cookie('last_known_locale', null) !== $lang) {
        cookie()->queue('last_known_locale', $lang, 60 * 24 * 365);
    }

    return $next($request);
}
```

`routes/web.php`
```php
Route::get('{path}', function (Request $request) {
    $lang = $request->cookie('last_known_locale', null);

    $lang ??= config('app.fallback_locale');

    return redirect()->to($lang.'/'.$request->path());
})
    ->where('path', '^(?!(en|fr)).*');
```

`index.blade.php`
```php
<?php

use function Laravel\Folio\name;

name('home');
?>
```

`php artisan folio:list`
```bash
GET       /en ....... home › resources/views/pages/index.blade.php
GET       /fr ....... home › resources/views/pages/index.blade.php
```

**Comment by driesvints** [comment]
I do understand your use case but right now we don't have immediate plans for this as it could potentially really complicate the internals of Folio. If you could come up with a non-breaking PR that wouldn't overly complicate Folio's codebase we could maybe give it a shot. But it's unlikely we'll be working on this ourselves anytime soon, sorry.
