### ISSUE TITLE
Auth::user() returns null in Folio pages

### ISSUE THREAD

**Issue by KbaylonH** [laravel/folio#142]
### Folio Version

1.1

### Laravel Version

10.10

### PHP Version

8.1.23

### Description

Hello, I am encountering an issue when using Auth::user() or auth()->user() in Blade templates with Laravel Folio. Even though I have applied the auth middleware to all routes in FolioServiceProvider, the authenticated user is not being passed correctly to the Blade templates, and Auth::user() returns null.

### Steps To Reproduce

1. Apply the auth middleware in FolioServiceProvider.
2. Attempt to access the authenticated user in a Folio page.
3. The Auth::user() or auth()->user() call returns null, even though the user is authenticated.

**Comment by inmanturbo** [comment]
how exactly are you applying the auth middleware? are you including a guard, i.e `auth:sanctum` or `auth:web`? have you also applied the `web` middleware?

**Comment by KbaylonH** [comment]
@inmanturbo No, I did not include any guard.

I applied the auth middleware as follows:

```php
// FolioServiceProvider.php

Folio::path(resource_path('views/pages'))->middleware([
    '*' => ['auth'],
]);
```

... And when I tried to access the authenticated user in a Folio page like this I got the issue: 
```php
// resources/views/pages/users.blade.php
<?php
use function Laravel\Folio\name;

name('users.index');

dd(auth()->user()); // <--- returns null
?>
<div>I am the users page</div>
```

Am I using Folio wrong?

**Comment by KbaylonH** [comment]
Hi, I found my error. I should have used the render function to access the authenticated user.
