### ISSUE TITLE
There's already a "Laravel Folio"

### ISSUE THREAD

**Issue by smilingpeanut** [laravel/folio#36]
### Folio Version

1.0.0

### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

You may want to reach out to this developer:
[https://github.com/nonoesp/laravel-folio](https://github.com/nonoesp/laravel-folio)

### Steps To Reproduce

N/A

**Comment by taylorotwell** [comment]
Hey there - I own the trademark to "Laravel".
