### ISSUE TITLE
Could other files work eg *.blade.md or *.blade.html

### ISSUE THREAD

**Issue by njames** [laravel/folio#40]
Firstly - I think this is brilliant for super simple sites that don't need too much complexity on the routing front. 

As I said in the title - could other file types work? 

That would be awesome. 

Priority: NTH (Nice to have)

**Comment by njames** [comment]
I think I meant just plain *.html but I take the point. Thanks :)

**Comment by nikspyratos** [comment]
In case anyone ends up here from search engines: [Folio Markdown](https://github.com/snellingio/folio-markdown) will allow the use of `.blade.md`.
