### ISSUE TITLE
Could folio have a 'cut down' version of laravel

### ISSUE THREAD

**Issue by njames** [laravel/folio#42]
So from a brand new installation of Laravel I just added folio and vapor-core and had a site up in "no time".

That got me wondering - if I had a simple content site - like documentation of a product say, could all the "other stuff" like models, controllers be removed from the base framework? Does this impact the size of the lambda function?

I see there is scope for models so this is only for the simple site use case.

**Comment by driesvints** [comment]
Thanks. Right now we don't have plans for this sorry.
