### ISSUE TITLE
Use Folio and controllers for the same parent route

### ISSUE THREAD

**Issue by alexmanase** [laravel/folio#53]
I think it would be nice to use Folio base routing and the controller based routing for the same parent route.

**Example**

The url `/products` is created using Laravel Folio and the route `/products/{id}` being used with a controller in the `web.php` file.

**Comment by taylorotwell** [comment]
I'm not sure of your question or issue.

**Comment by alexmanase** [comment]
@taylorotwell let me try explaining it with a better example.

## Context

For Folio you have this configuration:

```php
Folio::route(
    path: resource_path('view/custom-pages'),
    uri: '/'
);
```

For another route you have this callback.

```php
// web.php
Route::get('/home', function () {
    return view('pages.home');
});
```

## Issue

With this example `/home` is not going to work because the main path for pages (aka `/`) is going to be used only by Folio. It's going to work only if I create a file inside `views/custom-pages`, but I need to use a "traditional" way for `/home` (in this scenario).

Please let me know, if you need more details. I think it would be a really nice feature.

I can try to make a PR if you consider that this feature is worth it.

**Comment by alexmanase** [comment]
I've looked at my project and at Folio and there is no issue.
