### ISSUE TITLE
Top level components are not receiving parameter values

### ISSUE THREAD

**Issue by farez** [laravel/folio#58]
### Folio Version

1.0.0-beta.1

### Laravel Version

10.16.1

### PHP Version

8.1

### Description

Not sure if this is a bug or not, but if a view component is used inside a Folio page as the 'top level' component, e.g. as a layout component, parameters do not get passed to the component. But it does get passed through once it's nested inside another div.

E.g. this doesn't pass the `title` parameter:

```
<x-app-layout title="Videos">

   ...

</x-app-layout>
```

But this does:
```
<div>
    <x-app-layout title="Videos">
        
        ...

    </x-app-layout>
</div>
```

### Steps To Reproduce

1. Create a component that accepts a parameter and outputs it in the component.
2. Use the component inside a Folio page as the top-level component. Pass along the parameter.
3. Result: the parameter's value is not passed to the component.
4. Now, in the Folio page, wrap the component with div tags.
5. Refresh the output.
6. Result: the parameter's value is now passed to the component.

**Comment by nunomaduro** [comment]
On the `app.blade.php` layout, did you set the `title` as `@prop`?
