### ISSUE TITLE
Please add query string support

### ISSUE THREAD

**Issue by hazwan91** [laravel/folio#81]
Is it possible to add support for query string?

I read the current docs on GitHub and it is nice to have segment, multiple segment, route model binding, and customizing the model key. I might have miss it but I can't find how to use query string on Laravel Folio. Somehow I need it on most of my project and I fall in love with this Laravel Folio.

**Comment by hiddenLadder** [comment]
maybe you should use livewire for that

**Comment by nunomaduro** [comment]
Not sure I follow - could you re-create this issue and point to its equivalent in regular Laravel routing (https://laravel.com/docs/10.x/routing)? Thanks!
