### ISSUE TITLE
Feature Idea - Add Function for Metadata 

### ISSUE THREAD

**Issue by tcampbPPU** [laravel/folio#82]
## Feature Request Idea

I think it would be great if we could add metadata to a folio page. I am thinking of how it works in Nuxt with Nuxt Content if your familiar (https://content.nuxtjs.org/guide/writing/markdown). 

In Nuxt your `content` directory (similar concept to the `resources/views/pages/*`) which may look like
```md
---
type: 'blog'
title: 'Title of the page'
description: 'meta description of the page'
---

<!-- Content of the page -->
  ```
A purpose for these front-matter metadata is to be able to query the pages and display them in a list. For example, if you have a blog you may want to display a list of all the blog posts that based on some criteria.

an implementation of this could be something like
```php
collect(Folio::pages())->where('type', 'blog')->sortBy('createdAt')->take(5);
```

More on the metadata part...idk exactly how it would work best, maybe something like:
```php
<?php

use function Laravel\Folio\{metadata};

metadata([
    'type' => 'blog',
    'title' => 'Dashboard',
    'description' => 'meta description of the page',
]);

?>

<div>
    Blogs
</div>
```

**Comment by nunomaduro** [comment]
Thank you for this feature suggestion. We are going to put this on hold for now.

**Comment by Susros** [comment]
Oh, this is the feature I have been looking for exactly. Looks like this feature is on hold. Did you find the alternative solution @tcampbPPU ?

**Comment by tcampbPPU** [comment]
> Oh, this is the feature I have been looking for exactly. Looks like this feature is on hold. Did you find the alternative solution @tcampbPPU ?

no, also not that i've checked or looked more into tbh 😅. I would be interested in this still, but like inferred by my original comment I primary use Nuxt for these static content pages, so it it not a huge breaking point for me.

**Comment by inmanturbo** [comment]
> Oh, this is the feature I have been looking for exactly. Looks like this feature is on hold. Did you find the alternative solution @tcampbPPU ?

You can easily create a simple class which stores an array or collection of metadata and the route (path or name) in the service container.

You could even make a helper function like described above which takes in an array stores it in the container along with the current route.

You could also check out https://github.com/spatie/laravel-navigation and which does something similar, but for links and menus.

You could just call `Menu::add()` on each page. 🤷
