### ISSUE TITLE
Problem with subdomain

### ISSUE THREAD

**Issue by RenatoVi** [laravel/folio#95]
### Folio Version

1.0.0

### Laravel Version

10.20

### PHP Version

8.2

### Description

I'm having this problem when trying to use subdomain following the documentation. Could it be a bug? that is not injecting the subdomain into the blade?

### Steps To Reproduce

```
app/Providers/FolioServiceProvider.php

class FolioServiceProvider extends ServiceProvider
{
    ...
    public function boot(): void
    {
        Folio::path(resource_path('views/pages'))->middleware([
            '*' => [
                //
            ],
        ]);

        Folio::domain('{account}.laravel.docker')
            ->path(resource_path('views/pages/painel'));
    }
    ...    
}
```

resources/views/pages/painel/index.blade.php

```
<div class="row">
    <div class="col-md-12">
        <h1 class="page-header">Hello {{$account}} </h1>
    </div>
</div>
```

Error:
`Undefined variable $account`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
